# ???????? ????????? ??????????
spring.application.name=user-service
server.port=8081

# DataSource
spring.datasource.url=jdbc:postgresql://postgres:5432/hw
spring.datasource.username=${POSTGRES_USER:user}
spring.datasource.password=${POSTGRES_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Liquibase
spring.liquibase.enabled=true
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Kafka
spring.kafka.bootstrap-servers=kafka:9092
app.kafka.topic.user-events=user-service-topic

# Eureka Client
eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.prefer-ip-address=true
